root: true
extends: eslint:recommended
parser: "babel-eslint"
env:
  node: true 
  jquery: true
rules:
  brace-style: 
    - warn
    - "stroustrup" # start of "else" blocks on a new line
  indent: 
    - warn
    - 2 # use 2 spaces for indentation
  linebreak-style: 
    - warn
    - "unix" # use "\n" for line breaks
  no-console: 
    - off # allow usage of "console" object for logging
  no-unused-vars:
    - warn