root: true
plugins:
  - security
extends: 
  - eslint:recommended
  - plugin:security/recommended
parser: "babel-eslint"
env:
  node: true 
  jquery: true
rules:
  brace-style: 
    - warn
    - "stroustrup" # start of "else" blocks on a new line
  indent: 
    - warn
    - 2 # use 2 spaces for indentation
    - "SwitchCase": 1
  linebreak-style: 
    - warn
    - "unix" # use "\n" for line breaks
  no-console: 
    - off # allow usage of "console" object for logging
  no-unused-vars:
    - warn
